import type { Transaction } from "../types";

export const transactions: Transaction[] = [
  {
    id: "trx-1",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TOPUP",
    title: "Top up approved",
    amount: 2500000,
    direction: "IN",
    counterparty: "BCA Virtual Account",
    status: "SUCCESS",
    createdAt: "2026-05-28T06:30:00.000Z",
  },
  {
    id: "trx-2",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TRANSFER",
    title: "Transfer to Rama",
    amount: 350000,
    direction: "OUT",
    counterparty: "Rama Putra",
    status: "SUCCESS",
    createdAt: "2026-05-29T10:30:00.000Z",
  },
  {
    id: "trx-3",
    walletId: "wal-2",
    userId: "usr-1",
    type: "PAYMENT",
    title: "Payment code used",
    amount: 780000,
    direction: "OUT",
    counterparty: "Jakarta Hotel",
    status: "SUCCESS",
    createdAt: "2026-06-01T02:15:00.000Z",
  },
  {
    id: "trx-4",
    walletId: "wal-3",
    userId: "usr-2",
    type: "PAYMENT",
    title: "Merchant settlement",
    amount: 1250000,
    direction: "OUT",
    counterparty: "Office Supplies",
    status: "SUCCESS",
    createdAt: "2026-06-02T04:10:00.000Z",
  },
  {
    id: "trx-5",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TRANSFER",
    title: "Transfer to Rama",
    amount: 350000,
    direction: "OUT",
    counterparty: "Rama Putra",
    status: "SUCCESS",
    createdAt: "2026-05-29T10:30:00.000Z",
  },
  {
    id: "trx-6",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TRANSFER",
    title: "Transfer to Rama",
    amount: 350000,
    direction: "OUT",
    counterparty: "Rama Putra",
    status: "SUCCESS",
    createdAt: "2026-05-29T10:30:00.000Z",
  },
  {
    id: "trx-7",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TRANSFER",
    title: "Transfer to Rama",
    amount: 350000,
    direction: "OUT",
    counterparty: "Rama Putra",
    status: "SUCCESS",
    createdAt: "2026-05-29T10:30:00.000Z",
  },
  {
    id: "trx-8",
    walletId: "wal-1",
    userId: "usr-1",
    type: "TRANSFER",
    title: "Transfer to Rama",
    amount: 350000,
    direction: "OUT",
    counterparty: "Rama Putra",
    status: "SUCCESS",
    createdAt: "2026-05-29T10:30:00.000Z",
  },
];
